version: '3'

services:
    es:
        image: elasticsearch
        ports:
            - 9200:9200
    thing:
        build: .
        ports:
            - 80:8080
        volumes: 
            - ./cert:/cert

