version: '3'

services:
    elasticsearch:
        image: elasticsearch
        ports:
            - 9200:9200
    thing:
        build: .
        ports:
            - 80:8080
        depends_on:
            - elasticsearch

